package PruebaMapeoBiblioteca;
// Generated 18-ene-2020 12:09:19 by Hibernate Tools 4.3.1



/**
 * Socio generated by hbm2java
 */
public class Socio  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private String apellidos;
     private Integer telefono;

    public Socio() {
    }

	
    public Socio(String dni) {
        this.dni = dni;
    }
    public Socio(String dni, String nombre, String apellidos, Integer telefono) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.telefono = telefono;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }




}


